/**
 * Report type definitions
 *
 * Reports are generated by student and validated by GitHub Action.
 * See .verified-dev/CONTRACTS.md for schema version rules.
 */

/**
 * Machine-readable report written to .verified/report.json
 */
export interface MachineReport {
  /** Schema version - bump only with coordination */
  schema_version: '0.1.0';
  /** Report generation timestamp (ISO 8601) */
  generated_at: string;
  /** Assignment identifier */
  assignment_id: string;
  /** Session ID for the report generation */
  session_id: string;
  /** Integrity verification result */
  integrity: IntegrityStatus;
  /** Aggregated time statistics */
  time: TimeStats;
  /** Burst detection summary */
  bursts: BurstStats;
  /** Checkpoint summary */
  checkpoints: CheckpointInfo;
  /** Unverified changes detected */
  unverified_changes: UnverifiedChange[];
}

/**
 * Integrity status in report
 */
export interface IntegrityStatus {
  /** Overall integrity pass/fail */
  passed: boolean;
  /** Specific issues found (empty if passed) */
  issues: IntegrityIssue[];
}

/**
 * Individual integrity issue
 */
export interface IntegrityIssue {
  /** Issue type code */
  type: 'missing_log' | 'broken_hash_chain' | 'missing_checkpoint' | 'missing_assignment';
  /** Human-readable description */
  description: string;
  /** Related event ID if applicable */
  event_id?: string;
}

/**
 * Time statistics in report
 */
export interface TimeStats {
  /** Total focused time across all sessions (seconds) */
  total_focused_seconds: number;
  /** Total active time across all sessions (seconds) */
  total_active_seconds: number;
  /** Number of sessions tracked */
  session_count: number;
  /** First session start time (ISO 8601) */
  first_session_start: string | null;
  /** Last session end time (ISO 8601) */
  last_session_end: string | null;
}

/**
 * Burst detection statistics in report
 */
export interface BurstStats {
  /** Total number of burst events detected */
  total_count: number;
  /** Breakdown by severity */
  by_severity: {
    low: number;
    medium: number;
    high: number;
  };
}

/**
 * Checkpoint information in report
 */
export interface CheckpointInfo {
  /** Number of checkpoints found */
  count: number;
  /** Latest checkpoint ID */
  latest_checkpoint_id: string | null;
}

/**
 * Unverified change entry in report
 */
export interface UnverifiedChange {
  /** File path that was changed */
  path: string;
  /** Change type */
  change_type: 'added' | 'modified' | 'deleted';
  /** Checkpoint after which this was detected */
  detected_after_checkpoint: string;
}

/**
 * Assignment metadata stored in .verified/assignment.json
 * This is committed by the instructor/assignment setup.
 */
export interface AssignmentMetadata {
  /** Unique assignment identifier */
  assignment_id: string;
  /** Assignment name/title */
  assignment_name: string;
  /** ISO 8601 timestamp of assignment creation */
  created_at: string;
  /** Optional: expected file patterns for the assignment */
  expected_files?: string[];
}
